# Generated by Django 5.1.7 on 2025-05-01 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castingcalls', '0014_calendaritem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaritem',
            name='calendar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='castingcalls.calendar'),
        ),
        migrations.AddField(
            model_name='calendaritem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
