# Generated by Django 5.1.7 on 2025-05-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castingcalls', '0015_calendaritem_calendar_calendaritem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='castings',
        ),
    ]
